<?php
/*
 * Copyright 2013 by Jerrick Hoang, Ivy Xing, Sam Roberts, James Cook, 
 * Johnny Coster, Judy Yang, Jackson Moniaga, Oliver Radwan, 
 * Maxwell Palmer, Nolan McNair, Taylor Talmage, and Allen Tucker. 
 * This program is part of RMH Homebase, which is free software.  It comes with 
 * absolutely no warranty. You can redistribute and/or modify it under the terms 
 * of the GNU General Public License as published by the Free Software Foundation
 * (see <http://www.gnu.org/licenses/ for more information).
 * 
 */

	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			About
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<p><strong>Background</strong><br /><br />
				  
	      <a href="http://code.google.com/p/rmh-homebase/">
	<i>Homebase</i></a> is a web-based volunteer management and scheduling system developed at <a href="http://www.bowdoin.edu/computer-science" target="_blank">
	Bowdoin College</a> for the <a href="http://www.rmhportland.org/" target="_blank">Ronald McDonald House in Portland, Maine</a>.  
				 It was first implemented in 2008 by four Bowdoin Students (Oliver Radwan, Maxwell Palmer, Nolan McNair, and Taylor Talmage) and
				a Bowdoin instructor (Allen Tucker).  It was adapted in 2011 for the Ronald McDonald House in Wilmington, Delaware, 
				and its functionality was extended in 2012 by three more Bowdoin students (Jackson Moniaga, Johnny Coster, and Judy Wang) and the instructor. 
				More information about the <i>Homebase</i> project can be found at <a href="http://myopensoftware.org/content/software-projects" target="_blank">myopensoftware.org</a> 
				and in articles published by 
				<a href="http://pressherald.mainetoday.com/story.php?id=174400&ac" TARGET="_BLANK">the Portland Press Herald</a> and 
				<a href="http://www.bowdoin.edu/news/archives/1bowdoincampus/005118.shtml" target="_BLANK"> Bowdoin College</a>.  
				
				<p>The current version was developed by and the instructor in fall 2013 with the assistance of RMH staff
				members Gabrielle Booth and Karla Prouty.
				
				<p>
				This project was supported by Bowdoin College as part of its ongoing commitment to serving the common good. It was inspired by the 
				<a href="http://www.hfoss.org/">Humanitarian Free and Open Source (HFOSS) Project</a>, which aims to "build a community of academic computing departments,
				IT corporations, and local and global humanitarian and community organizations dedicated to
				building and using Free and Open Source Software to benefit humanity."
				
				
 
 <p><strong>System Access and Reuse</strong><br /><br />
Because Homebase must protect the privacy of individual volunteers at the Ronald McDonald House, access to the system by non-volunteers is
limited.  If you are a volunteer and have forgotten your Username or Password, please contact the <a href="mailto:housemngr@rmhportland.org">House Manager</a>.
                </p>
				<p> Homebase is free and open source software (see <a href="http://code.google.com/p/rmh-homebasecivi/" target="_blank">http://code.google.com/p/rmh-homebasecivi/</a>).  
				From this site, its source code can be freely downloaded and adapted
				 to fit the volunteer scheduling needs of other nonprofit organizations.  For more information about the capabilities or adaptability of Homebase to other settings, please contact
either <a href="mailto:allen@myopensoftware.org">Allen Tucker</a> or visit the website <a href="http://myopensoftware.org/content/software-projects" target="_blank">http://myopensoftware.org</a>.
				</p>
				<!-- below is the footer that we're using currently-->
				
			</div>
		<?PHP include('footer.inc');?>
		</div>
	</body>
</html>
