<!-- Begin Footer -->
<br /><br />
<div align="center">
    <div align="center" style="border:dashed 1px #999; width:80%;">

        <p style="font-size:xx-small">Copyright &copy; 2008-2013 by Jerrick Hoang, Ivy Xing, Sam Roberts, James Cook, Johnny Coster, Jackson Moniaga, Judy Yang, 
            Maxwell Palmer, Oliver Radwan, Nolan McNair, Taylor Talmadge, and <a href="mailto:allen@myopensoftware.org>">Allen Tucker</a>.  
            <i>Homebase</i> is free open source software and it comes with absolutely no warranty.  
            You can redistribute and/or modify this software under the terms of the
            <a href="http://www.gnu.org/licenses/gpl.html"> GNU General Public License</a>.
        </p>
    </div>
</div>
<!-- End Footer -->