<?php
/*
 * Copyright 2015 by Adrienne Beebe, Connor Hargus, Phuong Le, 
 * Xun Wang, and Allen Tucker. This program is part of RMHP-Homebase, which is free 
 * software.  It comes with absolutely no warranty. You can redistribute and/or 
 * modify it under the terms of the GNU General Public License as published by the 
 * Free Software Foundation (see <http://www.gnu.org/licenses/ for more information).
 */
	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			Help - <?PHP echo($_GET['helpPage']); ?>
		</title>
		<link rel="stylesheet" href="tutorial/styles.css" type="text/css" />
	</head>

	<body>
		<div id="container">
			<div id="content">
				<div align="center"><p><a href="?">Help Home</a></p></div>

				<?PHP
					//This array associates pages a person might be viewing
					//with the help page we assume they want. Note: it might be important
					//for each page to include within it a link to the 'home help' website
					//to allow us to get them to material somewhere else they might want.
					//you can guarantee a link to the home site by simply linking to
					//help.php with no variable passed through the GET method.
//developer templage
$assocHelp['helpPageTemplate.php']='helpPageTemplate.inc.php';
					
					//basic pages
					$assocHelp['login.php']='login.inc.php';
					$assocHelp['index.php']='index.inc.php';
					$assocHelp['about.php']='index.inc.php';
					$assocHelp['volunteerLog.php']='volunteerLogHelp.inc.php';
					
					//person editing, searching
					$assocHelp['personSearch.php']='searchPersonHelp.inc.php';
					$assocHelp['personEdit.php']='editPersonHelp.inc.php';
					$assocHelp['personAdd.php']='addPersonHelp.inc.php';
					
					//calendar managing
					$assocHelp['calendar.php']='manageCalendarHelp.inc.php';
					$assocHelp['addWeek.php']='generateWeekHelp.inc.php';
					$assocHelp['cancelShift.php']='cancelPersonShiftHelp.inc.php';
					$assocHelp['addSlotToShift.php']='addSlotToShiftHelp.inc.php';
					$assocHelp['addPersonToShift.php']='addPersonToShiftHelp.inc.php';
					$assocHelp['subCallList.php']='subCallListHelp.inc.php';
					$assocHelp['addNotes.php']='calendarNotesHelp.inc.php';
					$assocHelp['navigateThroughWeeks.php']='navigateThroughWeeksHelp.inc.php';
					
					// master schedule managing
					$assocHelp['viewSchedule.php']='schedulingHelp.inc.php';
					
					// other
					$assocHelp['quickStartGuide.php']='quickStartGuideHelp.inc.php';
					$assocHelp['reports.php']='reportsHelp.inc.php';
					$assocHelp['dataExport.inc.php']='dataExportHelp.inc.php';

					//personal home page
					$assocHelp['index.php']='indexHelp.inc.php';


					//Now if we have an undefined array value for the key they've passed us
					//what happens? This means that the page they're looking for help on doesn't have a
					//specific help page we defined above. So we pass them to the index page to see if they can find help from there.
					$loc = substr($_GET['helpPage'],strpos($_GET['helpPage'],"/")+1);
					if(!$assocHelp[$loc])
						$assocHelp[$loc]='index.inc.php';

					//now this line actually snags the tutorial data they're requesting and displays it.
					include('tutorial/'.$assocHelp[$loc]);
				?>

				
			</div>
		<?PHP include('footer.inc');?>
		</div>
	</body>
</html>
